// India destination data — used across the app
export const INDIA_DESTINATIONS = [
  {
    id: "kashmir",
    name: "Kashmir",
    region: "North India",
    tagline: "Heaven on Earth",
    emoji: "🏔️",
    image: "https://images.unsplash.com/photo-1562462181-9a5f3c2a36bc?q=80&w=2070&auto=format&fit=crop",
    bestTime: "Apr–Jun, Sep–Nov",
    budgetRange: "₹8,000 – ₹25,000 / day",
    famousFood: ["Rogan Josh", "Yakhni", "Kashmiri Pulao", "Kahwa tea"],
    highlights: ["Dal Lake Shikara ride", "Gulmarg snow activities", "Pahalgam trek", "Mughal gardens"],
    hiddenGem: "Gurez Valley — a pristine Himalayan paradise with zero tourists",
    transport: { airport: "Sheikh ul-Alam Airport, Srinagar", train: "Udhampur (then road)", duration: "~2h flight from Delhi" },
    tags: ["Mountains", "Adventure", "Honeymoon", "Nature"],
    gradient: "from-blue-900/80 to-cyan-900/80",
    color: "#60a5fa",
  },
  {
    id: "goa",
    name: "Goa",
    region: "West India",
    tagline: "Sun, Sand & Soul",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=2074&auto=format&fit=crop",
    bestTime: "Nov–Feb",
    budgetRange: "₹3,000 – ₹15,000 / day",
    famousFood: ["Fish Curry Rice", "Prawn Balchão", "Bebinca", "Feni"],
    highlights: ["Baga & Palolem beaches", "Old Goa churches", "Spice plantations", "Night markets"],
    hiddenGem: "Divar Island — a quiet backwater island with Portuguese heritage",
    transport: { airport: "Goa International Airport (Mopa)", train: "Madgaon/Vasco da Gama station", duration: "~1.5h flight from Mumbai" },
    tags: ["Beach", "Party", "Culture", "Food"],
    gradient: "from-yellow-900/80 to-orange-900/80",
    color: "#fb923c",
  },
  {
    id: "kerala",
    name: "Kerala",
    region: "South India",
    tagline: "God's Own Country",
    emoji: "🌴",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=2070&auto=format&fit=crop",
    bestTime: "Sep–Mar",
    budgetRange: "₹4,000 – ₹20,000 / day",
    famousFood: ["Sadhya", "Appam & Stew", "Karimeen Pollichathu", "Puttu & Kadala"],
    highlights: ["Alleppey houseboat", "Munnar tea gardens", "Periyar wildlife", "Kovalam beach"],
    hiddenGem: "Vythiri in Wayanad — misty rainforest with zero crowd",
    transport: { airport: "Cochin International Airport", train: "Excellent rail network across Kerala", duration: "~2h flight from Delhi" },
    tags: ["Nature", "Backwaters", "Wellness", "Ayurveda"],
    gradient: "from-green-900/80 to-teal-900/80",
    color: "#4ade80",
  },
  {
    id: "jaipur",
    name: "Jaipur",
    region: "Rajasthan",
    tagline: "The Pink City",
    emoji: "🏰",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed31459?q=80&w=2070&auto=format&fit=crop",
    bestTime: "Oct–Mar",
    budgetRange: "₹2,500 – ₹15,000 / day",
    famousFood: ["Dal Baati Churma", "Laal Maas", "Ghewar", "Pyaaz Kachori"],
    highlights: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar"],
    hiddenGem: "Abhaneri step-well (Chand Baori) — an 800-year old architectural marvel",
    transport: { airport: "Jaipur International Airport", train: "Jaipur Junction (major hub)", duration: "~5h by train from Delhi" },
    tags: ["Heritage", "Culture", "Royalty", "Shopping"],
    gradient: "from-rose-900/80 to-pink-900/80",
    color: "#f472b6",
  },
  {
    id: "ladakh",
    name: "Ladakh",
    region: "North India",
    tagline: "Land of High Passes",
    emoji: "🏜️",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=2070&auto=format&fit=crop",
    bestTime: "Jun–Sep",
    budgetRange: "₹5,000 – ₹18,000 / day",
    famousFood: ["Thukpa", "Momos", "Butter Tea (Gur Gur Chai)", "Skyu"],
    highlights: ["Pangong Tso lake", "Khardung La pass", "Nubra Valley", "Thiksey Monastery"],
    hiddenGem: "Tso Moriri — a high altitude lake even more serene than Pangong with far fewer visitors",
    transport: { airport: "Kushok Bakula Rimpochee Airport, Leh", train: "No direct train — road via Manali/Srinagar", duration: "~1.5h flight from Delhi" },
    tags: ["Adventure", "Camping", "Spiritual", "Bikes"],
    gradient: "from-violet-900/80 to-indigo-900/80",
    color: "#a78bfa",
  },
  {
    id: "varanasi",
    name: "Varanasi",
    region: "Uttar Pradesh",
    tagline: "City of Light & Moksha",
    emoji: "🛕",
    image: "https://images.unsplash.com/photo-1561361058-c24e018330a5?q=80&w=2070&auto=format&fit=crop",
    bestTime: "Oct–Mar",
    budgetRange: "₹1,500 – ₹8,000 / day",
    famousFood: ["Banarasi Paan", "Tamatar Chaat", "Lassi", "Kachori Sabzi"],
    highlights: ["Dashashwamedh Ghat Aarti", "Sunrise boat ride", "Vishwanath Temple", "Sarnath"],
    hiddenGem: "Ramnagar Fort — a forgotten royal fort across the Ganges with stunning sunset views",
    transport: { airport: "Lal Bahadur Shastri Airport", train: "Varanasi Junction (major rail hub)", duration: "~6h by train from Delhi" },
    tags: ["Spiritual", "Culture", "History", "Photography"],
    gradient: "from-amber-900/80 to-yellow-900/80",
    color: "#fbbf24",
  },
  {
    id: "meghalaya",
    name: "Meghalaya",
    region: "Northeast India",
    tagline: "Abode of Clouds",
    emoji: "☁️",
    image: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?q=80&w=2070&auto=format&fit=crop",
    bestTime: "Oct–May",
    budgetRange: "₹2,000 – ₹10,000 / day",
    famousFood: ["Jadoh", "Tungrymbai", "Nakham Bitchi", "Dohneiiong"],
    highlights: ["Living root bridges", "Dawki river", "Mawsmai caves", "Nohkalikai Falls"],
    hiddenGem: "Nongkhnum Island — the largest river island in Northeast India",
    transport: { airport: "Shillong Airport (Umroi)", train: "Guwahati station then 2h road", duration: "~2h flight from Kolkata" },
    tags: ["Nature", "Adventure", "Offbeat", "Caves"],
    gradient: "from-emerald-900/80 to-cyan-900/80",
    color: "#34d399",
  },
  {
    id: "andaman",
    name: "Andaman Islands",
    region: "Bay of Bengal",
    tagline: "Emerald Islands of Paradise",
    emoji: "🐠",
    image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2070&auto=format&fit=crop",
    bestTime: "Oct–May",
    budgetRange: "₹4,000 – ₹18,000 / day",
    famousFood: ["Fish Tikka", "Prawn Masala", "Coconut curry", "Fresh seafood"],
    highlights: ["Radhanagar Beach", "Cellular Jail", "Scuba diving", "Bioluminescent plankton"],
    hiddenGem: "Barren Island — India's only active volcano, accessible by boat from Port Blair",
    transport: { airport: "Veer Savarkar Airport, Port Blair", train: "No train — only ship or flight", duration: "~2h flight from Chennai" },
    tags: ["Beach", "Diving", "Islands", "Snorkeling"],
    gradient: "from-sky-900/80 to-blue-900/80",
    color: "#38bdf8",
  },
  {
    id: "hyderabad",
    name: "Hyderabad",
    region: "Telangana",
    tagline: "City of Nawabs & Tech",
    emoji: "🍖",
    image: "https://images.unsplash.com/photo-1572731948-b5d57a6f793c?q=80&w=2070&auto=format&fit=crop",
    bestTime: "Oct–Feb",
    budgetRange: "₹2,000 – ₹12,000 / day",
    famousFood: ["Hyderabadi Biryani", "Haleem", "Mirchi Ka Salan", "Irani Chai"],
    highlights: ["Charminar", "Golconda Fort", "Hussain Sagar", "Salar Jung Museum"],
    hiddenGem: "Ananthagiri Hills — a misty forest getaway just 90km from Hyderabad",
    transport: { airport: "Rajiv Gandhi International Airport", train: "Secunderabad/Hyderabad Deccan", duration: "~1.5h flight from Mumbai" },
    tags: ["Food", "History", "Tech", "Culture"],
    gradient: "from-red-900/80 to-orange-900/80",
    color: "#f87171",
  },
];

export type Destination = typeof INDIA_DESTINATIONS[number];
